name: Update Activity
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update-activity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo "<!--START_SECTION:activity-->" > activity.md
          curl -s "https://api.github.com/users/gyanendra-chaudhary/events" | jq -r '.[] | select(.type == "PushEvent" or .type == "PullRequestEvent" or .type == "IssuesEvent") | .created_at + ": " + .type' | head -5 >> activity.md
          echo "<!--END_SECTION:activity-->" >> activity.md
          sed -i '/<!--START_SECTION:activity-->/,/<!--END_SECTION:activity-->/!b;//!d;/<!--START_SECTION:activity-->/r activity.md' README.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add README.md
          git commit -m "docs: Update activity log [skip ci]" || exit 0
          git push
